#!/bin/bash

# this script take in one or more filenames as arguments
# and copy these files to home directory
# if no arguments are supplied, it prompts the user to provide filenames

# if no arguments are supplied then prompt for arguments
# else assign all arguments to FILENAME variable
if [ -z "$1" ]; then
	read -p "enter file names: " FILENAMES
else
	FILENAMES=$@
fi

# for each file name, copy to home directory
for FILE in $FILENAMES
do	
	cp $FILE ~ # or use $HOME to refer to home directory
done

	
