#!/bin/bash

# this script transforms the string 'cn=lara,dc=example,dc=com' such that the username (lara) is extracted
# the result will be transformed to lower case, and stored in variable name $USER
# $USER is echoed at the end of the script

STRING="cn=lara,dc=example,dc=com"

# split string by '=' and ',', print 2nd field
USER=$(echo $STRING | awk -F '[=,]' '{ print $2 }')
# replace any upper case characters
USER=$(echo $USER | tr [:upper:] [:lower:])

echo user name is: $USER