#!/bin/bash

# this exercise reads lines of a txt file (with lines in LDAP format, same as ex4)
# for each line in txt file, extract name of user, and create a user
# also write line to a target file 

for LINE in `cat exercise5.txt`
do
    # from exercise 4
    USER=$(echo $LINE | awk -F '[=,]' '{ print $2 }' | tr [:upper:] [:lower:])
    echo line $LINE written to file
    echo user $USER created
done

exit 0