#!/bin/bash

# this script aims to copy files from /var/log/messages to /var/log/messages.old
# then delete contents of /var/log/messages

cp /var/log/messages /var/log/messages.old
cat /dev/null > /var/log/message    # this command wipes contents of dir after > symbol [safe method, does not interrupt processes]

# implementation of script using Variablesbas
LOGFILE=/var/log/messages
cp $LOGFILE $LOGFILE.old
cat /dev/null > $LOGFILE

exit 0


